# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2abd8f4da1be7ab338eb3772943ce87d5f61504f3a18098c586aa0dfa07e412c5bd74bd9c5e09a0b47826be466cc4b30a6d6cab717d19a4d3957ff56bf296739

test:
  secret_key_base: d78d19828c2ce6956145dc243a582e794396709758e07929bb03556999a1d7a1b879c1e65775de893e090d2445c0377449c8ca3a9edc47cef000c5cac01e6804

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
